### ISSUE TITLE
IIS wfastcgi OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by lw-bmc** [alexsilva/wfastcgi#1]
I'm running a Flask/wfastcgi API on IIS (Azure). The API normally works fine, taking less than 1 second to respond to most requests. Randomly, however, it fails to respond at all. I've create a simple HTTP client which sends 1000 HTTP requests to the API in parallel. Majority finish within a couple of seconds, but a few timeout after 2 minutes. I've looked through the wfastcgi logs and found this error entry:

2021-11-19 09:41:07.692850: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "e:\wwwroot\cvdprevent\cvdprevent-api\venv\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "e:\wwwroot\cvdprevent\cvdprevent-api\venv\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2021-11-19 09:41:07.770975: Running on_exit tasks
2021-11-19 09:41:07.802225: wfastcgi.py 3.0.0 closed

Any ideas what could be causing this? 

Versions: 
Python: 3.9.6
wfastcgi: 3.0.0
Flask: 2.0.2
Windows 2019 Dataserver
IIS 10.0

**Comment by alexsilva** [comment]
This interface only responds to one request at a time. For example 4 processes respond in parallel to 4 requests at a time. When processes fail to meet demand, these failures often happen. Maybe configuring IIS to wait longer helps but there is a long queue of requests and response time drops a lot.

Ideally, you would use a server that supports modern interfaces like wsgi. fastcgi is an improved cgi and converting fastcgi to wsgi is very bad for system performance.

**Comment by lw-bmc** [comment]
> This interface only responds to one request at a time. For example 4 processes respond in parallel to 4 requests at a time. When processes fail to meet demand, these failures often happen. Maybe configuring IIS to wait longer helps but there is a long queue of requests and response time drops a lot.
> 
> Ideally, you would use a server that supports modern interfaces like wsgi. fastcgi is an improved cgi and converting fastcgi to wsgi is very bad for system performance.

@alexsilva thanks for your reply. Timeout does not seem to be a problem. The problem is that a response is never returned, and the client can hang. I presume that if IIS encountered an issue, it would at least send an error response

**Comment by jorditruji** [comment]
Hello,

I'm facing the exact same error when deploying a Dash app with IIS and wfastcgi. 

Did you find any solution to this error?

**Comment by alexsilva** [comment]
There has been very little change since the last release. Only microsoft developers will be able to solve this.
https://github.com/microsoft/PTVS/commits/main/Python/Product/WFastCgi/wfastcgi.py

https://pypi.org/user/Steve.Dower/
